title: "xrcyz's blog"
author: "Blog Author"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "blog.md" }
  - {file: "contact.md" }

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Twitter, icon: twitter, url: "https://twitter.com/planet403"}
  - {title: YouTube, icon: youtube, url: "https://www.youtube.com/channel/UCUUthZRHCLVwzUplFGyJyeA"}
  - {title: OpenProcessing, icon: code, url: "https://openprocessing.org/user/43936?view=sketches"}
  - {title: Github, icon: github, url: "https://github.com/xrcyz"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
